apiVersion: v1
kind: Namespace
metadata:
  namespace: network-aware-controllers
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: networktopology-controller
  namespace: network-aware-controllers
